application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

handlers:
- url: /_ah/spi/.*
  script: store_locator_api.APPLICATION
- url: /css/
  static_dir: templates/css
- url: /images/
  static_dir: templates/images
- url: /js
  static_dir: templates/js/
- url: /index_files/
  static_dir: templates/index_files
- url: /app
  script: api.application
- url: /shop/.*
  script: shop.application
- url: /.*
  script: main.application